[tool.poetry]
name = "essencia-core"
version = "0.1.4"
description = ""
authors = ["arantesdv <arantesdv@me.com>"]

[tool.poetry.dependencies]
python = "^3.7"
starlette = "^0.14.2"
deta = "^0.8"
typesystem = "^0.2.4"
bootstrap4 = "^0.1.0"
Jinja2 = "^3.0.1"
MarkupSafe = "^2.0.1"
uvicorn = "^0.14.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
