[tool.poetry]
name = "bstops-security"
version = "0.0.4"
description = ""
authors = ["walker <walkerIVI@gmail.com>"]
license = "MIT"
packages = [ { include = "bstops" },]

[tool.poetry.dependencies]
python = "^3.7"
pycrypto = "^2.6.1"
pyotp = "^2.6.0"
qrcode = "^6.1"
bitarray = "^2.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
