[tool.poetry]
name = "rtt"
version = "0.5.0"
description = ""
authors = ["tlonny <t@lonny.io>"]

[tool.poetry.dependencies]
python = "^3.9"
tabulate = "^0.8.9"

[tool.poetry.dev-dependencies]
black = "^21.6b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
rtt = "rtt:cli"